-- ============================================================================
-- Construction Reference Tables
-- Provides prescriptive component data for a unit builder application.
-- ============================================================================

-- ── Engine Types ─────────────────────────────────────────────────────────────

CREATE TABLE engine_types (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                TEXT NOT NULL UNIQUE,
  name                TEXT NOT NULL,
  tech_base           tech_base_enum NOT NULL,
  rules_level         rules_level_enum NOT NULL,
  weight_multiplier   NUMERIC(4,3) NOT NULL CHECK (weight_multiplier > 0),
  ct_crits            SMALLINT NOT NULL DEFAULT 6 CHECK (ct_crits >= 0),
  st_crits            SMALLINT NOT NULL DEFAULT 0 CHECK (st_crits >= 0),
  intro_year          INT
);

INSERT INTO engine_types (slug, name, tech_base, rules_level, weight_multiplier, ct_crits, st_crits, intro_year)
VALUES
  ('standard-fusion', 'Standard Fusion',   'inner_sphere', 'introductory', 1.000, 6, 0, 2020),
  ('xl-is',           'XL Engine (IS)',     'inner_sphere', 'standard',     0.500, 6, 3, 3035),
  ('xl-clan',         'XL Engine (Clan)',   'clan',         'standard',     0.500, 6, 2, 2824),
  ('light',           'Light Engine',       'inner_sphere', 'standard',     0.750, 6, 2, 3062),
  ('compact',         'Compact Engine',     'inner_sphere', 'advanced',     1.500, 3, 0, 3068),
  ('xxl-is',          'XXL Engine (IS)',    'inner_sphere', 'experimental', 0.333, 6, 6, 3055),
  ('ice',             'Internal Combustion','inner_sphere', 'introductory', 2.000, 6, 0, NULL),
  ('fuel-cell',       'Fuel Cell',          'inner_sphere', 'advanced',     1.200, 6, 0, 2470),
  ('primitive-fusion','Primitive Fusion',   'primitive',    'advanced',     1.200, 6, 0, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tech_base = EXCLUDED.tech_base, rules_level = EXCLUDED.rules_level,
  weight_multiplier = EXCLUDED.weight_multiplier, ct_crits = EXCLUDED.ct_crits,
  st_crits = EXCLUDED.st_crits, intro_year = EXCLUDED.intro_year;

-- ── Armor Types ──────────────────────────────────────────────────────────────

CREATE TABLE armor_types (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                TEXT NOT NULL UNIQUE,
  name                TEXT NOT NULL,
  tech_base           tech_base_enum NOT NULL,
  rules_level         rules_level_enum NOT NULL,
  points_per_ton      NUMERIC(5,2) NOT NULL CHECK (points_per_ton > 0),
  crits               SMALLINT NOT NULL DEFAULT 0 CHECK (crits >= 0),
  intro_year          INT
);

INSERT INTO armor_types (slug, name, tech_base, rules_level, points_per_ton, crits, intro_year)
VALUES
  ('standard',         'Standard Armor',           'inner_sphere', 'introductory', 16.00,  0, NULL),
  ('ferro-fibrous-is', 'Ferro-Fibrous (IS)',       'inner_sphere', 'standard',     17.92, 14, 2571),
  ('ferro-fibrous-clan','Ferro-Fibrous (Clan)',     'clan',         'standard',     19.20,  7, 2820),
  ('light-ferro',      'Light Ferro-Fibrous',      'inner_sphere', 'standard',     16.96,  7, 3067),
  ('heavy-ferro',      'Heavy Ferro-Fibrous',      'inner_sphere', 'advanced',     24.96, 21, 3069),
  ('stealth',          'Stealth Armor',            'inner_sphere', 'advanced',     16.00, 12, 3063),
  ('reactive',         'Reactive Armor',           'inner_sphere', 'advanced',     16.00, 14, 3065),
  ('hardened',         'Hardened Armor',            'inner_sphere', 'advanced',      8.00,  0, 3047),
  ('primitive',        'Primitive Armor',           'primitive',    'advanced',     14.22,  0, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tech_base = EXCLUDED.tech_base, rules_level = EXCLUDED.rules_level,
  points_per_ton = EXCLUDED.points_per_ton, crits = EXCLUDED.crits, intro_year = EXCLUDED.intro_year;

-- ── Structure Types ──────────────────────────────────────────────────────────

CREATE TABLE structure_types (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                TEXT NOT NULL UNIQUE,
  name                TEXT NOT NULL,
  tech_base           tech_base_enum NOT NULL,
  rules_level         rules_level_enum NOT NULL,
  weight_fraction     NUMERIC(5,4) NOT NULL CHECK (weight_fraction > 0),
  crits               SMALLINT NOT NULL DEFAULT 0 CHECK (crits >= 0),
  intro_year          INT
);

INSERT INTO structure_types (slug, name, tech_base, rules_level, weight_fraction, crits, intro_year)
VALUES
  ('standard',         'Standard Structure',     'inner_sphere', 'introductory', 0.1000,  0, NULL),
  ('endo-steel-is',    'Endo Steel (IS)',         'inner_sphere', 'standard',     0.0500, 14, 2487),
  ('endo-steel-clan',  'Endo Steel (Clan)',       'clan',         'standard',     0.0500,  7, 2820),
  ('composite',        'Composite Structure',     'inner_sphere', 'experimental', 0.0500,  0, 3061),
  ('reinforced',       'Reinforced Structure',    'inner_sphere', 'advanced',     0.2000,  0, 3057),
  ('endo-composite-is','Endo-Composite (IS)',     'inner_sphere', 'advanced',     0.0750,  7, 3067)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tech_base = EXCLUDED.tech_base, rules_level = EXCLUDED.rules_level,
  weight_fraction = EXCLUDED.weight_fraction, crits = EXCLUDED.crits, intro_year = EXCLUDED.intro_year;

-- ── Heatsink Types ───────────────────────────────────────────────────────────

CREATE TABLE heatsink_types (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                TEXT NOT NULL UNIQUE,
  name                TEXT NOT NULL,
  tech_base           tech_base_enum NOT NULL,
  rules_level         rules_level_enum NOT NULL,
  dissipation         SMALLINT NOT NULL CHECK (dissipation > 0),
  crits               SMALLINT NOT NULL CHECK (crits >= 0),
  weight              NUMERIC(4,2) NOT NULL CHECK (weight > 0),
  intro_year          INT
);

INSERT INTO heatsink_types (slug, name, tech_base, rules_level, dissipation, crits, weight, intro_year)
VALUES
  ('single',      'Single Heat Sink',      'inner_sphere', 'introductory', 1, 1, 1.00, NULL),
  ('double-is',   'Double Heat Sink (IS)', 'inner_sphere', 'standard',     2, 3, 1.00, 3022),
  ('double-clan', 'Double Heat Sink (Clan)','clan',         'standard',     2, 2, 1.00, 2567),
  ('compact',     'Compact Heat Sink',     'inner_sphere', 'experimental', 1, 1, 0.50, 3068)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tech_base = EXCLUDED.tech_base, rules_level = EXCLUDED.rules_level,
  dissipation = EXCLUDED.dissipation, crits = EXCLUDED.crits, weight = EXCLUDED.weight,
  intro_year = EXCLUDED.intro_year;

-- ── Gyro Types ───────────────────────────────────────────────────────────────

CREATE TABLE gyro_types (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                TEXT NOT NULL UNIQUE,
  name                TEXT NOT NULL,
  tech_base           tech_base_enum,          -- NULL = tech-base-agnostic
  rules_level         rules_level_enum NOT NULL,
  weight_multiplier   NUMERIC(4,3) NOT NULL CHECK (weight_multiplier > 0),
  crits               SMALLINT NOT NULL DEFAULT 4 CHECK (crits >= 0),
  is_superheavy_only  BOOLEAN NOT NULL DEFAULT FALSE,
  intro_year          INT
);

INSERT INTO gyro_types (slug, name, tech_base, rules_level, weight_multiplier, crits, is_superheavy_only, intro_year)
VALUES
  ('standard',   'Standard Gyro',   NULL, 'introductory', 1.000, 4, FALSE, NULL),
  ('xl',         'XL Gyro',         NULL, 'standard',     0.500, 6, FALSE, 3067),
  ('compact',    'Compact Gyro',    NULL, 'advanced',     1.500, 2, FALSE, 3068),
  ('heavy-duty', 'Heavy-Duty Gyro', NULL, 'advanced',     2.000, 4, FALSE, 3067),
  ('superheavy', 'Superheavy Gyro', NULL, 'experimental', 1.000, 4, TRUE,  3076)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tech_base = EXCLUDED.tech_base, rules_level = EXCLUDED.rules_level,
  weight_multiplier = EXCLUDED.weight_multiplier, crits = EXCLUDED.crits,
  is_superheavy_only = EXCLUDED.is_superheavy_only, intro_year = EXCLUDED.intro_year;

-- ── Cockpit Types ────────────────────────────────────────────────────────────

CREATE TABLE cockpit_types (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                TEXT NOT NULL UNIQUE,
  name                TEXT NOT NULL,
  tech_base           tech_base_enum,          -- NULL = tech-base-agnostic
  rules_level         rules_level_enum NOT NULL,
  weight              SMALLINT NOT NULL DEFAULT 3 CHECK (weight > 0),
  crits               SMALLINT NOT NULL DEFAULT 5 CHECK (crits >= 0),
  intro_year          INT
);

INSERT INTO cockpit_types (slug, name, tech_base, rules_level, weight, crits, intro_year)
VALUES
  ('standard',        'Standard Cockpit',   NULL, 'introductory', 3, 5, NULL),
  ('small',           'Small Cockpit',      NULL, 'standard',     2, 4, 3067),
  ('command-console', 'Command Console',    NULL, 'advanced',     3, 6, 3031),
  ('torso-mounted',   'Torso-Mounted Cockpit', NULL, 'advanced',  4, 5, 3053),
  ('industrial',      'Industrial Cockpit', NULL, 'introductory', 3, 5, NULL),
  ('primitive',       'Primitive Cockpit',  NULL, 'advanced',     5, 5, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tech_base = EXCLUDED.tech_base, rules_level = EXCLUDED.rules_level,
  weight = EXCLUDED.weight, crits = EXCLUDED.crits, intro_year = EXCLUDED.intro_year;

-- ── Myomer Types ─────────────────────────────────────────────────────────────

CREATE TABLE myomer_types (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                TEXT NOT NULL UNIQUE,
  name                TEXT NOT NULL,
  tech_base           tech_base_enum,          -- NULL = tech-base-agnostic
  rules_level         rules_level_enum NOT NULL,
  intro_year          INT,
  properties          JSONB NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(properties) = 'object')
);

INSERT INTO myomer_types (slug, name, tech_base, rules_level, intro_year, properties)
VALUES
  ('standard',   'Standard Myomer',          NULL,           'introductory', NULL, '{}'),
  ('masc',       'MASC',                     NULL,           'standard',     3035, '{"tonnage_fraction": 0.05}'),
  ('tsm',        'Triple-Strength Myomer',   'inner_sphere', 'advanced',     3050, '{"heat_threshold": 9}'),
  ('industrial', 'Industrial Myomer',        NULL,           'introductory', NULL, '{}')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tech_base = EXCLUDED.tech_base, rules_level = EXCLUDED.rules_level,
  intro_year = EXCLUDED.intro_year, properties = EXCLUDED.properties;

-- ── Engine Weight Table ──────────────────────────────────────────────────────
-- Standard fusion engine weights from TechManual. Actual weight = standard_weight * engine_types.weight_multiplier.
-- Rounding: nearest half-ton per TechManual rules (applied by builder client).

CREATE TABLE engine_weight_table (
  rating              SMALLINT PRIMARY KEY CHECK (rating > 0),
  standard_weight     NUMERIC(6,2) NOT NULL CHECK (standard_weight > 0)
);

INSERT INTO engine_weight_table (rating, standard_weight) VALUES
  (10,  0.50), (15,  0.50), (20,  0.50), (25,  0.50), (30,  1.00),
  (35,  1.00), (40,  1.00), (45,  1.00), (50,  1.50), (55,  1.50),
  (60,  1.50), (65,  2.00), (70,  2.00), (75,  2.00), (80,  2.50),
  (85,  2.50), (90,  3.00), (95,  3.00), (100, 3.00), (105, 3.50),
  (110, 3.50), (115, 4.00), (120, 4.00), (125, 4.00), (130, 4.50),
  (135, 4.50), (140, 5.00), (145, 5.00), (150, 5.50), (155, 5.50),
  (160, 6.00), (165, 6.00), (170, 6.00), (175, 7.00), (180, 7.00),
  (185, 7.50), (190, 7.50), (195, 8.00), (200, 8.50), (205, 8.50),
  (210, 9.00), (215, 9.50), (220, 10.00),(225, 10.00),(230, 10.50),
  (235, 11.00),(240, 11.50),(245, 12.00),(250, 12.50),(255, 13.00),
  (260, 13.50),(265, 14.00),(270, 14.50),(275, 15.50),(280, 16.00),
  (285, 16.50),(290, 17.50),(295, 18.00),(300, 19.00),(305, 19.50),
  (310, 20.50),(315, 21.50),(320, 22.50),(325, 23.50),(330, 24.50),
  (335, 25.50),(340, 27.00),(345, 28.50),(350, 29.50),(355, 31.50),
  (360, 33.00),(365, 34.50),(370, 36.50),(375, 38.50),(380, 41.00),
  (385, 43.50),(390, 46.00),(395, 49.00),(400, 52.50)
ON CONFLICT (rating) DO UPDATE SET standard_weight = EXCLUDED.standard_weight;

-- ── Mech Internal Structure Table ────────────────────────────────────────────
-- Max armor per location = 2 * structure_points (except head max = 9).

CREATE TABLE mech_internal_structure (
  tonnage             SMALLINT PRIMARY KEY CHECK (tonnage > 0),
  head                SMALLINT NOT NULL CHECK (head > 0),
  center_torso        SMALLINT NOT NULL CHECK (center_torso > 0),
  side_torso          SMALLINT NOT NULL CHECK (side_torso > 0),
  arm                 SMALLINT NOT NULL CHECK (arm > 0),
  leg                 SMALLINT NOT NULL CHECK (leg > 0)
);

INSERT INTO mech_internal_structure (tonnage, head, center_torso, side_torso, arm, leg) VALUES
  (20,  3, 6,  5,  3,  4),
  (25,  3, 8,  6,  4,  6),
  (30,  3, 10, 7,  5,  7),
  (35,  3, 11, 8,  6,  8),
  (40,  3, 12, 10, 6,  10),
  (45,  3, 14, 11, 7,  11),
  (50,  3, 16, 12, 8,  12),
  (55,  3, 18, 13, 9,  13),
  (60,  3, 20, 14, 10, 14),
  (65,  3, 21, 15, 10, 15),
  (70,  3, 22, 15, 11, 15),
  (75,  3, 23, 16, 12, 16),
  (80,  3, 25, 17, 13, 17),
  (85,  3, 27, 18, 14, 18),
  (90,  3, 29, 19, 15, 19),
  (95,  3, 30, 20, 16, 20),
  (100, 3, 31, 21, 17, 21)
ON CONFLICT (tonnage) DO UPDATE SET
  head = EXCLUDED.head, center_torso = EXCLUDED.center_torso,
  side_torso = EXCLUDED.side_torso, arm = EXCLUDED.arm, leg = EXCLUDED.leg;
